import { Display } from "./Display";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <p>Layout:</p>
        <Display />
        {children}
      </body>
    </html>
  );
}
